version: "3.9"
services:
  db:
    image: postgres:16
    container_name: nodeapi-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${PGUSER:-postgres}
      POSTGRES_PASSWORD: ${PGPASSWORD:-postgres}
      POSTGRES_DB: ${PGDATABASE:-nodeapi}
    ports:
      - "${PGPORT:-5432}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PGUSER:-postgres} -d ${PGDATABASE:-nodeapi}"]
      interval: 5s
      timeout: 3s
      retries: 20
volumes:
  pgdata:
