// this code was generated by chatgpt 4

const express = require('express');
const { MongoClient } = require('mongodb');
const path = require('path');
const app = express();
const port = 5000;

app.use(express.json());

const uri = "mongodb://localhost:27017";
const client = new MongoClient(uri);
const dbName = "animalDB";
const collectionName = "animals";

// Function to setup the animals collection and data in MongoDB
async function setupAnimalData() {
    try {
        await client.connect();
        const db = client.db(dbName);
        const collection = db.collection(collectionName);

        // Check if the collection is empty and initialize data if it is
        const count = await collection.countDocuments();
        if (count === 0) {
            await collection.insertMany([
                { animalName: 'lion', imgName: 'lion.png' },
                { animalName: 'rabbit', imgName: 'rabbit.png' },
                { animalName: 'turtle', imgName: 'turtle.png' }
            ]);
            console.log('Animal data initialized.');
        } else {
            console.log('Animal data already exists.');
        }
    } finally {
        await client.close();
    }
}

// GET request handler to fetch animals from MongoDB
app.get('/api/animals', async (req, res) => {
    try {
        await client.connect();
        const db = client.db(dbName);
        const collection = db.collection(collectionName);
        const animals = await collection.find({}).toArray();
        res.json(animals);
    } catch (err) {
        res.status(500).send('Error fetching animal data');
    } finally {
        await client.close();
    }
});

// POST request handler
app.post('/api/image', (req, res) => {
    const { color, imgName } = req.body;
    const imagePath = path.join('public', color, imgName);
    res.sendFile(path.resolve(imagePath), err => {
        if (err) {
            res.status(404).send('Image not found');
        }
    });
});

app.listen(port, () => {
    console.log(`Server running at http://localhost:${port}`);
});

// Uncomment the line below to initialize the animal data in MongoDB
// setupAnimalData().catch(console.dir);
